function ShadowClass()
{
   this.createEmptyMovieClip("shadowsMC",1);
   this.setIlluminantPosition(0,0);
}
var p = ShadowClass.prototype = new MovieClip();
Object.registerClass("Shadow",ShadowClass);
p.objectRadius = 50;
p.illuminantRadius = 100;
p.setIlluminantPosition = function(x, y)
{
   this._illuminantX = x;
   this._illuminantY = y;
   this.update();
};
p.update = function()
{
   var mc = this.shadowsMC;
   mc.clear();
   mc.lineStyle(0,5263440,50);
   var x = this._illuminantX - this._x;
   var y = this._illuminantY - this._y;
   var d = Math.sqrt(x * x + y * y);
   var angle = Math.atan2(y,x);
   var cAngle = Math.cos(angle);
   var sAngle = Math.sin(angle);
   var k0 = cAngle;
   var k1 = - sAngle;
   var k2 = sAngle;
   var k3 = cAngle;
   var s = this.illuminantRadius;
   var r = this.objectRadius;
   var sa = (s + r) / d;
   var a = Math.asin(sa);
   var ca = Math.cos(a);
   var ta = Math.tan(a);
   var x1 = s * sa;
   var y1 = s * ca;
   var x2 = d - r * sa;
   var y2 = r * ca;
   var x3 = s / sa;
   var y3 = 0;
   var x4 = 1200;
   var y4 = (x4 - x3) * ta;
   var sb = (s - r) / d;
   var b = Math.asin(sb);
   var cb = Math.cos(b);
   var tb = Math.tan(b);
   var x5 = s * sb;
   var y5 = s * cb;
   var x6 = d + r * sb;
   var y6 = r * cb;
   var x7 = d + r / sb;
   var y7 = 0;
   var x8 = 1200;
   var y8 = (x8 - x7) * tb;
   var x1p = x1;
   var y1p = - y1;
   var x2p = x2;
   var y2p = - y2;
   var x4p = x4;
   var y4p = - y4;
   var x5p = x5;
   var y5p = - y5;
   var x6p = x6;
   var y6p = - y6;
   var x8p = x8;
   var y8p = - y8;
   var tx = x1;
   var ty = y1;
   var x1 = k0 * tx + k1 * ty;
   var y1 = k2 * tx + k3 * ty;
   var tx = x2;
   var ty = y2;
   var x2 = k0 * tx + k1 * ty;
   var y2 = k2 * tx + k3 * ty;
   var tx = x3;
   var ty = y3;
   var x3 = k0 * tx + k1 * ty;
   var y3 = k2 * tx + k3 * ty;
   var tx = x4;
   var ty = y4;
   var x4 = k0 * tx + k1 * ty;
   var y4 = k2 * tx + k3 * ty;
   var tx = x5;
   var ty = y5;
   var x5 = k0 * tx + k1 * ty;
   var y5 = k2 * tx + k3 * ty;
   var tx = x6;
   var ty = y6;
   var x6 = k0 * tx + k1 * ty;
   var y6 = k2 * tx + k3 * ty;
   var tx = x7;
   var ty = y7;
   var x7 = k0 * tx + k1 * ty;
   var y7 = k2 * tx + k3 * ty;
   var tx = x8;
   var ty = y8;
   var x8 = k0 * tx + k1 * ty;
   var y8 = k2 * tx + k3 * ty;
   var tx = x1p;
   var ty = y1p;
   var x1p = k0 * tx + k1 * ty;
   var y1p = k2 * tx + k3 * ty;
   var tx = x2p;
   var ty = y2p;
   var x2p = k0 * tx + k1 * ty;
   var y2p = k2 * tx + k3 * ty;
   var tx = x4p;
   var ty = y4p;
   var x4p = k0 * tx + k1 * ty;
   var y4p = k2 * tx + k3 * ty;
   var tx = x5p;
   var ty = y5p;
   var x5p = k0 * tx + k1 * ty;
   var y5p = k2 * tx + k3 * ty;
   var tx = x6p;
   var ty = y6p;
   var x6p = k0 * tx + k1 * ty;
   var y6p = k2 * tx + k3 * ty;
   var tx = x8p;
   var ty = y8p;
   var x8p = k0 * tx + k1 * ty;
   var y8p = k2 * tx + k3 * ty;
   mc.beginFill(5263440,10);
   mc.moveTo(x2,y2);
   mc.lineTo(x4,y4);
   mc.lineTo(x4p,y4p);
   mc.lineTo(x2p,y2p);
   mc.lineTo(x2,y2);
   mc.endFill();
   mc.beginFill(11579568,90);
   mc.moveTo(x6,y6);
   mc.lineTo(x6p,y6p);
   mc.lineTo(x7,y7);
   mc.lineTo(x6,y6);
   mc.endFill();
   mc.moveTo(x7,y7);
   mc.lineTo(x8,y8);
   mc.lineTo(x8p,y8p);
   mc.lineTo(x7,y7);
   trace("time: " + (getTimer() - start));
};
